version: '3.9'

services:

  db:
    image: postgres:latest

    restart: unless-stopped

    shm_size: 128mb

    environment:

      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

    ports:
      - 5432:5432

    volumes:
      - db_v:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    container_name: psql

    # networks:
    #   private:
    #     ipv4_address: 10.5.0.255
      
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - private

  ##ADMINER IS A PLACERHOLDER FOR THE PYTHON APPLICATION

networks: 
  private:
    driver: bridge
    name: backnet
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

  public:
    driver: bridge
    name: visiblenet
    ipam:
     config:
       - subnet: 192.168.0.0/16
         gateway: 192.168.0.1

volumes:
  db_v: